on:
  push:
    branches:
      - main

name: "🚀 Build package and publish to npm"

env:
  NODE_ENV: development

jobs:
  build:
    if: github.repository == 'kworz/ts-enip' # Disable action on forks
    name: 🧱 Build & release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 📚 Install Pnpm
        uses: pnpm/action-setup@v4

      - name: 📚 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      
      - name: ⛭ Setup Pnpm github registry
        run: pnpm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: 📚 Install Node dependencies
        run: pnpm install

      - name: 🧱 Run build scripts on all packages
        run: pnpm run build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}